### ISSUE TITLE
Weird Unicode symbols on Chrome setup page

### ISSUE THREAD

**Issue by tommorris** [aaronpk/IndieWeb-Reply-Browser-Extension#3]
In Chrome, there are weird Unicode symbols on the setup page.

Example:

![Screen Shot 2012-12-25 at 17 22 51](https://f.cloud.github.com/assets/175/30556/e1ef55a8-4eb7-11e2-82a1-05b904fdb270.png)

**Comment by tommorris** [comment]
Oh, wait, this is on @barnabywalters' version. I blame the Mimosas and mince pies.

**Comment by barnabywalters** [comment]
Weird, what version of chrome are you using?

**Comment by tommorris** [comment]
Version 23.0.1271.101 on Mac OS X 10.7.5

**Comment by barnabywalters** [comment]
Looks like there’s some weird encoding bug — no idea if it’s me or chrome, so I’m using HTML entities for those arrows now. There are a few other places where it needs changing too

**Comment by aaronpk** [comment]
Closing since it applies to barnaby's fork which has since moved to https://github.com/barnabywalters/web-action-hero-toolbelt
